version: "2"
services:
  node1:
    image: "node:8.9-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
      - MESSAGE=First instance
      - MSG_COLOR=#ff0000
    volumes:
      - ./src/:/home/node/app
    ports:
      - "8081:8080"
    #expose:
    #  - "8080"
    command: "node index.js"
    #command: "npm start"

  node2:
    image: "node:8.9-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
      - MESSAGE=Second instance
      - MSG_COLOR=#0000ff
    volumes:
      - ./src/:/home/node/app
    ports:
      - "8082:8080"
    command: "node index.js"

  proxy:
    image: "nginx:1.12-alpine"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "88:80"

